language: node_js
branches:
  only:
  - gh-pages
env:
  global:
  - SAUCE_USERNAME: ftft1885
  - secure: KC1UlwOFFUFvZdlpGIfDRgxCzmOu6/x5e1bqafv8poNZlYSPAy8kI5Og1kBw3HPzVwcNYdgGaYcNaXNpVtL7mB+ydverNyJpbfaPRORDPTdRzDinC2g0Skjqykcoy8KyfcxAG1zVlrifFA8tabHFrIV61RUel4RyKQwNXt8xK3o=
